### PR TITLE
Removed unecessary backslashes

### PR DESCRIPTION
**Pull request by cominixo**
The backslashes are not needed because there are commas.

### CODE REVIEW

**Comment by willtheorangeguy** [comment]
Please provide a description of what you changed and why.
Thanks!

**Review by willtheorangeguy — CHANGES_REQUESTED** [review]
Please add more information about the PR.

**Comment by cominixo** [comment]
Added description.

**Review by willtheorangeguy — APPROVED** [review]

**Comment by willtheorangeguy** [comment]
Thanks for changing that, I will merge the PR.

**Pull request merged**
